#ifndef SIZE_H_CONSTANTS
#define SIZE_H_CONSTANTS

#define FILE_TRANSFER_SIZE     1025
#define TEXT_TRANSFER_SIZE     513
#define TRANSFER_REQUEST_SIZE  517
#define TRANSFER_RESPONSE_SIZE 2
#define EOF_SIZE               1
#define CLOSE_CONNECTION_SIZE  1 
#define MAX_RECIEVABLE_SIZE    1025

#endif