#ifndef CONSTANTS
#define CONSTANTS

#define MAIN_VIEW_WIDTH 240
#define MAIN_VIEW_HEIGHT 170

#define EXP_VIEW_WIDTH 68
#define EXP_VIEW_HEIGHT 52

#define ROLL_STEP 0.5

#define PLAYER_POS_X 100
#define PLAYER_POS_Y 128

#define TILE_WIDTH 16
#define TILE_HEIGHT 16

#define PLAYER_TILE_OFFSET 7

enum TILE { VOID, CONCRETE_BLOCK, MINE_BLOCK, FINISH_BLOCK };

#endif