#ifndef ERROR_CODES_H_INCLUDED
#define ERROR_CODES_H_INCLUDED

#define SUCCESS 0
#define NEGATIVE_VALUE -1
#define NEGATIVE_BALANCE_WITHDRAW -2
#define ACCOUNT_WITHDRAW_LIMIT_REACHED -3
#define INACTIVE_ACCOUNT -4
#define CREDIT_CARD_LIMIT_REACHED -5

#endif // ERROR_CODES_H_INCLUDED
